[meta]
    name.dflt_lang = "en"
    name.en = "programmer - simple 2D"
    name.fr = "programmeur - 2D simple"

[graphics]
    file = "resources/simple-assets.png"

    [graphics.mobs]
        list = ["player", "scientist"]

        [graphics.mobs.player]
            id = @MOBS_PLAYERID@

        [graphics.mobs.player.downwards]
            frame-count = 1
            pos.x = 192
            pos.y = 16
            shift.x = -8
            shift.y = -8
            width = 16
            height = 16

        [graphics.mobs.player.upwards]
            frame-count = 1
            pos.x = 208
            pos.y = 16
            shift.x = -8
            shift.y = -8
            width = 16
            height = 16

        [graphics.mobs.player.rightwards]
            frame-count = 1
            pos.x = 208
            pos.y = 0
            shift.x = -8
            shift.y = -8
            width = 16
            height = 16

        [graphics.mobs.player.leftwards]
            frame-count = 1
            pos.x = 192
            pos.y = 0
            shift.x = -8
            shift.y = -8
            width = 16
            height = 16

        [graphics.mobs.player.uprightwards]
            frame-count = 1
            pos.x = 240
            pos.y = 0
            shift.x = -8
            shift.y = -8
            width = 16
            height = 16

        [graphics.mobs.player.upleftwards]
            frame-count = 1
            pos.x = 224
            pos.y = 0
            shift.x = -8
            shift.y = -8
            width = 16
            height = 16

        [graphics.mobs.player.downrightwards]
            frame-count = 1
            pos.x = 240
            pos.y = 16
            shift.x = -8
            shift.y = -8
            width = 16
            height = 16

        [graphics.mobs.player.downleftwards]
            frame-count = 1
            pos.x = 224
            pos.y = 16
            shift.x = -8
            shift.y = -8
            width = 16
            height = 16


        [graphics.mobs.scientist]
            id = @MOBS_SCIENTISTID@

        [graphics.mobs.scientist.downwards]
            frame-count = 1
            pos.x = 192
            pos.y = 16
            shift.x = -8
            shift.y = -8
            width = 16
            height = 16

        [graphics.mobs.scientist.upwards]
            frame-count = 1
            pos.x = 208
            pos.y = 16
            shift.x = -8
            shift.y = -8
            width = 16
            height = 16

        [graphics.mobs.scientist.rightwards]
            frame-count = 1
            pos.x = 208
            pos.y = 0
            shift.x = -8
            shift.y = -8
            width = 16
            height = 16

        [graphics.mobs.scientist.leftwards]
            frame-count = 1
            pos.x = 192
            pos.y = 0
            shift.x = -8
            shift.y = -8
            width = 16
            height = 16

        [graphics.mobs.scientist.uprightwards]
            frame-count = 1
            pos.x = 240
            pos.y = 0
            shift.x = -8
            shift.y = -8
            width = 16
            height = 16

        [graphics.mobs.scientist.upleftwards]
            frame-count = 1
            pos.x = 224
            pos.y = 0
            shift.x = -8
            shift.y = -8
            width = 16
            height = 16

        [graphics.mobs.scientist.downrightwards]
            frame-count = 1
            pos.x = 240
            pos.y = 16
            shift.x = -8
            shift.y = -8
            width = 16
            height = 16

        [graphics.mobs.scientist.downleftwards]
            frame-count = 1
            pos.x = 224
            pos.y = 16
            shift.x = -8
            shift.y = -8
            width = 16
            height = 16


    [graphics.tiles]
        list = ["chasm", "iron-tile", "concrete-tile", "tile-frame"]
        spacing.x = 32
        x-yshift = 0

        spacing.y = 32
        y-xshift = 0

        width = 32
        height = 32

        [graphics.tiles.chasm]
            id = @TILES_CHASMID@
            frame-count = 1
            pos.x = 32
            pos.y = 0

        [graphics.tiles.iron-tile]
            id = @TILES_IRONID@
            frame-count = 1
            pos.x = 0
            pos.y = 0

        [graphics.tiles.concrete-tile]
            id = @TILES_CONCRETEID@
            frame-count = 1
            pos.x = 0
            pos.y = 0

        [graphics.tiles.tile-frame]
            id = @TILES_FRAMEID@
            frame-count = 1
            pos.x = 160
            pos.y = 0

    [graphics.objects]
        list = ["button", "gate", "target"]

        [graphics.objects.button]
            id = @OBJECTS_BUTTONID@
            frame-count = 1
            pos.x = 65
            pos.y = 1
            width = 30
            height = 30
            shift.y = 1
            shift.x = 1

        [graphics.objects.gate]
            id = @OBJECTS_GATEID@
            frame-count = 1
            pos.x = 97
            pos.y = 1
            width = 30
            height = 30
            shift.y = 1
            shift.x = 1

        [graphics.objects.target]
            id = @OBJECTS_TARGETID@
            frame-count = 1
            pos.x = 128
            pos.y = 0
            width = 32
            height = 32
            shift.x = 0
